---
name: 사용자 글 작성
description: "{도메인}/u/{사용자_아이디}/{단축 경로} 형태의 사용자 정의 위치에 글 작성"
title: "[USER ARTICLE WRTING] 사용자 글 작성"
labels: user-article-writing
assignees: OUS-KR
body:
  - type: input
    id: user-id
    attributes:
      label: 사용자 아이디
      description: "등록한 본인의 사용자 아이디"
      placeholder: "예: my_user-id"
    validations:
      required: true
  - type: input
    id: short-url
    attributes:
      label: 단축 URL 경로
      description: "각 경로 이름은 20자리 이하의 영어 (a-z, A-Z), 숫자 (0-9), 하이픈 (-), 언더스코어 (_)로 구성되고, 시작과 끝은 영어 소문자와 숫자만 가능하며, 경로는 슬래시 (/)로 구분"
      placeholder: "예: instagram, sns/instagram, sns/instagram/profile, ..."
    validations:
      required: true
  #- type: checkboxes
  #  id: agreement
  #  attributes:
  #    label: 사용자 글 관련 설정
  #    description: 사용자 글 관련 다양한 옵션 설정
  #    options:
  #      - label: 댓글 시스템 활성화 여부
  #        required: true
  - type: textarea
    id: article
    attributes:
      label: 사용자 글
      description: 마크다운 기반의 글 작성 - [사용법: https://docs.github.com/ko/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-](https://docs.github.com/ko/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
      placeholder: 마크다운 기반의 글 작성
    validations:
      required: true
---
