---
name: 사용자 글 작성
description: "..."
title: "[USER ARTICLE WRTING] 사용자 글 작성"
labels: user-article-writing
assignees: OUS-KR
body:
  - type: input
    id: user-id
    attributes:
      label: 사용자 아이디
      description: "등록한 본인의 사용자 아이디"
      placeholder: "예: my_user-id"
    validations:
      required: true

  - type: checkboxes
    id: agreement
    attributes:
      label: 댓글 시스템 활성화
      description: Giscus 기반 댓글 시스템 활성화
      options:
        - label: 댓글 시스템 활성화 여부
          required: true

  - type: textarea
    id: article
    attributes:
      label: 사용자 글
      description: 마크다운 기반의 글 작성
      placeholder: 마크다운 기반의 글
    validations:
      required: true
---
