---
name: 사용자 글 삭제
description: "{도메인}/u/{사용자_아이디}/{단축 경로} 형태의 사용자 글 삭제"
title: "[USER ARTICLE WRTING] 사용자 글 삭제"
labels: user-article-deletion
assignees: OUS-KR
body:
  - type: input
    id: user-id
    attributes:
      label: 사용자 아이디
      description: "등록한 본인의 사용자 아이디"
      placeholder: "예: my_user-id"
    validations:
      required: true
---
