name: User register by issue
  
on:
  issues:
    types: [opened, edited, reopened, closed]
    
jobs:
  user-short-url-register:
    if: contains(github.event.issue.labels.*.name, 'user-short-url-register')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
    
    - name: Extract user ID, original URL, and short URL from issue body
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: extract
      run: |
        BODY="${{ github.event.issue.body }}"
        USER_ID=$(echo "$BODY" | awk '/### 사용자 아이디/{getline; getline; print}' | xargs | sed 's/^[ \t]*//;s/[ \t]*$//')
        ORIGINAL_URL=$(echo "$BODY" | awk '/### 원본 URL/{getline; getline; print}' | xargs | sed 's/^[ \t]*//;s/[ \t]*$//')
        SHORT_PATH=$(echo "$BODY" | awk '/### 단축 URL 경로/{getline; getline; print}' | xargs | sed 's/^[ \t]*//;s/[ \t]*$//')
        
        echo "Extracted USER_ID: $USER_ID"
        echo "Extracted ORIGINAL_URL: $ORIGINAL_URL"
        echo "Extracted SHORT_PATH: $SHORT_PATH"
        
        if [[ ! "$USER_ID" =~ ^[a-z0-9][a-z0-9_-]{1,28}[a-z0-9]$ ]]; then
          echo "올바르지 않은 아이디 형식" > comment.md
          gh issue comment "$ISSUE_NUMBER" -F comment.md
          echo "user_id=" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        if [[ ! "$ORIGINAL_URL" =~ ^https?:// ]]; then
          echo "올바르지 않은 원본 URL 형식" > comment.md
          gh issue comment "$ISSUE_NUMBER" -F comment.md
          echo "original_url=" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        validate_segment() {
          SEGMENT="$1"
          echo "SEGMENT: $SEGMENT"
          
          if [[ "$SEGMENT" =~ ^[a-zA-Z0-9](?:[a-zA-Z0-9_-]{0,18}[a-zA-Z0-9])?$ ]]; then
            return 1
          fi
          return 0
        }
        
        IFS='/' read -ra PARTS <<< "$SHORT_PATH"
        for SEGMENT in "${PARTS[@]}"; do
          if ! validate_segment "$SEGMENT"; then
            echo "올바르지 않은 단축 URL 경로 형식: $SEGMENT" > comment.md
            gh issue comment "$ISSUE_NUMBER" -F comment.md
            echo "short_path=" >> $GITHUB_OUTPUT
            exit 1
          fi
        done
        
        echo "user_id=$USER_ID" >> $GITHUB_OUTPUT
        echo "original_url=$ORIGINAL_URL" >> $GITHUB_OUTPUT
        echo "short_path=$SHORT_PATH" >> $GITHUB_OUTPUT
