name: User deletion by issue
  
on:
  issues:
    types: [opened]
    
jobs:
  user-deletion:
    if: contains(github.event.issue.labels.*.name, 'user-deletion')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
        
    - name: Extract user ID from issue body
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: extract
      run: |
        BODY="${{ github.event.issue.body }}"
        
        USER_ID=$(echo "$BODY" | grep -v '^\s*$' | tail -n1 | sed 's/^[ \t]*//;s/[ \t]*$//')
        echo "Extracted USER_ID: $USER_ID"
        
        if [[ ! "$USER_ID" =~ ^[a-z0-9][a-z0-9_-]{1,28}[a-z0-9]$ ]]; then
          echo "올바르지 않은 아이디 형식" > comment.md
          gh issue comment "$ISSUE_NUMBER" -F comment.md
          echo "user_id=" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        echo "user_id=$USER_ID" >> $GITHUB_OUTPUT
        
    - name: Check if user exists
      env:
        USER_ID: ${{ steps.extract.outputs.user_id }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ ! -d "public/u/$USER_ID" ]; then
          echo "존재하지 않는 사용자 아이디: **$USER_ID**" > comment.md
          gh issue comment "$ISSUE_NUMBER" -F comment.md
          exit 1
        fi
      
    - name: Check GitHub user ownership
      env:
        USER_ID: ${{ steps.extract.outputs.user_id }}
        GITHUB_ID: ${{ github.event.issue.user.login }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        META_FILE="public/u/$USER_ID/meta.json"
        
        GITHUB_ID_META_FILE=$(jq -r '.github_id // empty' "$META_FILE")
        if [ "$GITHUB_ID" != "$GITHUB_ID_META_FILE" ]; then
          echo "권한이 없습니다" > comment.md
          gh issue comment "$ISSUE_NUMBER" -F comment.md
          exit 1
        fi
        
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Commit and push to main
      env:
        USER_ID: ${{ steps.extract.outputs.user_id }}
      run: |
        git checkout main
        git rm -r "public/u/$USER_ID" || true
        git rm -r "registered/users/$GITHUB_ID" || true
        git commit -m "Delete user directory for $USER_ID and registered user info" || echo "Nothing to commit"
        git push origin main
        
    - name: Commit and push to gh-pages
      env:
        USER_ID: ${{ steps.extract.outputs.user_id }}
      run: |
        git fetch origin gh-pages
        git switch gh-pages || git checkout -b gh-pages
        
        git rm -r u/$USER_ID || true
        git commit -m "Delete user data: $USER_ID" || echo "Nothing to commit"
        git push origin gh-pages
        
    - name: Comment on issue
      env:
        USER_ID: ${{ steps.extract.outputs.user_id }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "사용자 **$USER_ID** 삭제 완료" > comment.md
        gh issue comment ${{ github.event.issue.number }} -F comment.md
