name: Deploy to gh-pages

on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
        
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Deploy to gh-pages branch
      run: |
        git fetch origin gh-pages
        git switch gh-pages || git checkout -b gh-pages
        
        git rm -rf .
        
        git checkout main -- public
        mv public/* .
        rm -rf public
        
        git add .
        git commit -m "Deploy site from main/public to gh-pages"
        git push origin gh-pages --force