name: User register by issue
  
on:
  issues:
    types: [opened, edited, reopened, closed]
    
jobs:
  user-short-url-register:
    if: contains(github.event.issue.labels.*.name, 'user-short-url-register')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
    
    - name: Extract user ID, original URL, and short URL from issue body
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: extract
      run: |
        BODY="${{ github.event.issue.body }}"
        USER_ID=$(echo "$BODY" | awk '/### 사용자 아이디/{getline; getline; print}' | xargs)
        ORIGINAL_URL=$(echo "$BODY" | awk '/### 원본 URL/{getline; getline; print}' | xargs)
        SHORT_PATH=$(echo "$BODY" | awk '/### 단축 URL 경로/{getline; getline; print}' | xargs)
        
        echo "Extracted USER_ID: $USER_ID"
        echo "Extracted ORIGINAL_URL: $ORIGINAL_URL"
        echo "Extracted SHORT_PATH: $SHORT_PATH"
        
        echo "user_id=$USER_ID" >> $GITHUB_OUTPUT
        echo "original_url=$ORIGINAL_URL" >> $GITHUB_OUTPUT
        echo "short_path=$SHORT_PATH" >> $GITHUB_OUTPUT