name: User register by issue
  
on:
  issues:
    types: [opened, closed, reopened]
    
jobs:
  user-register:
    if: contains(github.event.issue.labels.*.name, 'user-register')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
        
    - name: Extract user ID from issue body
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: extract
      run: |
        echo "${{ github.event.issue.body }}" > issue_body.txt
        
        USER_ID=$(grep -v '^\s*$' issue_body.txt | tail -n1 | sed 's/^[ \t]*//;s/[ \t]*$//')
        echo "Extracted USER_ID: $USER_ID"
        
        if [[ ! "$USER_ID" =~ ^[a-z0-9]([a-z0-9\-_]{1,28})[a-z0-9]$ ]]; then
          echo "올바르지 않은 아이디 형식" > comment.md
          gh issue comment "$ISSUE_NUMBER" -F comment.md
          echo "user_id=" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        echo "user_id=$USER_ID" >> $GITHUB_OUTPUT
        
    - name: Check if user already exists
      env:
        USER_ID: ${{ steps.extract.outputs.user_id }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ -d "public/u/$USER_ID" ]; then
          echo "사용할 수 없는 사용자 아이디: **$USER_ID**" > comment.md
          gh issue comment "$ISSUE_NUMBER" -F comment.md
          exit 1
        fi
        
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Create user page
      env:
        USER_ID: ${{ steps.extract.outputs.user_id }}
      run: |
        mkdir -p "public/u/$USER_ID"
        sed "s/\${USER_ID}/$USER_ID/g" templates/user.html > "public/u/$USER_ID/index.html"
        
    - name: Commit and push to gh-pages
      env:
        USER_ID: ${{ steps.extract.outputs.user_id }}
      run: |
        git fetch origin gh-pages
        git switch gh-pages || git checkout -b gh-pages
        
        mkdir -p u
        git checkout main -- public/u/$USER_ID
        mv public/u/$USER_ID u/
        
        git add u/$USER_ID
        git commit -m "Add user page: $USER_ID"
        git push origin gh-pages
        
    - name: Comment on issue
      env:
        USER_ID: ${{ steps.extract.outputs.user_id }}
      run: |
        echo "사용자 **$USER_ID** 등록 완료" > comment.md
        gh issue comment ${{ github.event.issue.number }} -F comment.md