name: User register by issue
  
on:
  issues:
    types: [opened, edited]
    
jobs:
  user-short-url-register:
    if: contains(github.event.issue.labels.*.name, 'user-short-url-register')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
    
    - name: Extract user ID, original URL, and short URL from issue body
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: extract
      run: |
        BODY="${{ github.event.issue.body }}"
        USER_ID=$(echo "$BODY" | grep -A1 '사용자 아이디' | tail -n1 | xargs)
        ORIGINAL_URL=$(echo "$BODY" | grep -A1 '원본 URL' | tail -n1 | xargs)
        SHORT_PATH=$(echo "$BODY" | grep -A1 '단축 URL 경로' | tail -n1 | xargs)
        
        echo "user_id=$USER_ID" >> $GITHUB_OUTPUT
        echo "original_url=$ORIGINAL_URL" >> $GITHUB_OUTPUT
        echo "short_path=$SHORT_PATH" >> $GITHUB_OUTPUT